// lib/color.ts

export const colorClasses = {
  blue: {
    text: 'text-blue-800',
    border: 'border-blue-300',
    lightBg: 'bg-blue-50',
    badge: 'bg-blue-100 text-blue-800',
    dot: 'bg-blue-500',
    ring: 'ring-blue-200',
    solid: 'bg-blue-500',
    solidHover: 'hover:bg-blue-600',
  },
  green: {
    text: 'text-green-800',
    border: 'border-green-300',
    lightBg: 'bg-green-50',
    badge: 'bg-green-100 text-green-800',
    dot: 'bg-green-500',
    ring: 'ring-green-200',
    solid: 'bg-green-500',
    solidHover: 'hover:bg-green-600',
  },
  purple: {
    text: 'text-purple-800',
    border: 'border-purple-300',
    lightBg: 'bg-purple-50',
    badge: 'bg-purple-100 text-purple-800',
    dot: 'bg-purple-500',
    ring: 'ring-purple-200',
    solid: 'bg-purple-500',
    solidHover: 'hover:bg-purple-600',
  },
  teal: {
    text: 'text-teal-800',
    border: 'border-teal-300',
    lightBg: 'bg-teal-50',
    badge: 'bg-teal-100 text-teal-800',
    dot: 'bg-teal-500',
    ring: 'ring-teal-200',
    solid: 'bg-teal-500',
    solidHover: 'hover:bg-teal-600',
  },
  yellow: {
    text: 'text-yellow-800',
    border: 'border-yellow-300',
    lightBg: 'bg-yellow-50',
    badge: 'bg-yellow-100 text-yellow-800',
    dot: 'bg-yellow-500',
    ring: 'ring-yellow-200',
    solid: 'bg-yellow-600',
    solidHover: 'hover:bg-yellow-700',
  },
  pink: {
    text: 'text-pink-800',
    border: 'border-pink-300',
    lightBg: 'bg-pink-50',
    badge: 'bg-pink-100 text-pink-800',
    dot: 'bg-pink-500',
    ring: 'ring-pink-200',
    solid: 'bg-pink-500',
    solidHover: 'hover:bg-pink-600',
  },
  indigo: {
    text: 'text-indigo-800',
    border: 'border-indigo-300',
    lightBg: 'bg-indigo-50',
    badge: 'bg-indigo-100 text-indigo-800',
    dot: 'bg-indigo-500',
    ring: 'ring-indigo-200',
    solid: 'bg-indigo-500',
    solidHover: 'hover:bg-indigo-600',
  },
  orange: {
    text: 'text-orange-800',
    border: 'border-orange-300',
    lightBg: 'bg-orange-50',
    badge: 'bg-orange-100 text-orange-800',
    dot: 'bg-orange-500',
    ring: 'ring-orange-200',
    solid: 'bg-orange-500',
    solidHover: 'hover:bg-orange-600',
  },
  cyan: {
    text: 'text-cyan-800',
    border: 'border-cyan-300',
    lightBg: 'bg-cyan-50',
    badge: 'bg-cyan-100 text-cyan-800',
    dot: 'bg-cyan-500',
    ring: 'ring-cyan-200',
    solid: 'bg-cyan-500',
    solidHover: 'hover:bg-cyan-600',
  },
  red: {
    text: 'text-red-800',
    border: 'border-red-300',
    lightBg: 'bg-red-50',
    badge: 'bg-red-100 text-red-800',
    dot: 'bg-red-500',
    ring: 'ring-red-200',
    solid: 'bg-red-500',
    solidHover: 'hover:bg-red-600',
  },
  rose: {
    text: 'text-rose-800',
    border: 'border-rose-300',
    lightBg: 'bg-rose-50',
    badge: 'bg-rose-100 text-rose-800',
    dot: 'bg-rose-500',
    ring: 'ring-rose-200',
    solid: 'bg-rose-500',
    solidHover: 'hover:bg-rose-600',
  },
  brown: {
    text: 'text-amber-800',
    border: 'border-amber-300',
    lightBg: 'bg-amber-50',
    badge: 'bg-amber-100 text-amber-800',
    dot: 'bg-amber-800',
    ring: 'ring-amber-200',
    solid: 'bg-amber-800',
    solidHover: 'hover:bg-amber-900',
  },
  lime: {
    text: 'text-lime-800',
    border: 'border-lime-300',
    lightBg: 'bg-lime-50',
    badge: 'bg-lime-100 text-lime-800',
    dot: 'bg-lime-500',
    ring: 'ring-lime-200',
    solid: 'bg-lime-500',
    solidHover: 'hover:bg-lime-700',
  },
  gray: {
    text: 'text-gray-800',
    border: 'border-gray-300',
    lightBg: 'bg-gray-50',
    badge: 'bg-gray-100 text-gray-800',
    dot: 'bg-gray-500',
    ring: 'ring-gray-200',
    solid: 'bg-gray-500',
    solidHover: 'hover:bg-gray-600',
  },
  peach: {
    text: 'text-orange-800',
    border: 'border-orange-300',
    lightBg: 'bg-orange-50',
    badge: 'bg-orange-100 text-orange-800',
    dot: 'bg-orange-500',
    ring: 'ring-orange-200',
    solid: 'bg-orange-500',
    solidHover: 'hover:bg-orange-600',
  },
  navy: {
    text: '[color:#1e3a8a]',
    border: '[border-color:#1e3a8a]',
    lightBg: '[background-color:#dbeafe]',
    badge: '[background-color:#dbeafe] [color:#1e3a8a]',
    dot: '[background-color:#1e3a8a]',
    ring: 'ring-blue-200',
    solid: '[background-color:#1e3a8a] dark:[background-color:#60a5fa]',
    solidHover: 'hover:[background-color:#1e40af] dark:hover:[background-color:#93c5fd]',
  },
  maroon: {
    text: '[color:#7f1d1d]',
    border: '[border-color:#7f1d1d]',
    lightBg: '[background-color:#fee2e2]',
    badge: '[background-color:#fee2e2] [color:#7f1d1d]',
    dot: '[background-color:#7f1d1d]',
    ring: 'ring-red-200',
    solid: '[background-color:#7f1d1d] dark:[background-color:#f87171]',
    solidHover: 'hover:[background-color:#991b1b] dark:hover:[background-color:#fca5a5]',
  },
  gold: {
    text: '[color:#854d0e]',
    border: '[border-color:#ca8a04]',
    lightBg: '[background-color:#fef3c7]',
    badge: '[background-color:#fef3c7] [color:#854d0e]',
    dot: '[background-color:#ca8a04]',
    ring: 'ring-amber-200',
    solid: '[background-color:#ca8a04] dark:[background-color:#facc15]',
    solidHover: 'hover:[background-color:#b45309] dark:hover:[background-color:#fde047]',
  },
  mint: {
    text: '[color:#0f766e]',
    border: '[border-color:#5eead4]',
    lightBg: '[background-color:#ccfbf1]',
    badge: '[background-color:#ccfbf1] [color:#0f766e]',
    dot: '[background-color:#5eead4]',
    ring: 'ring-teal-200',
    solid: '[background-color:#0f766e] dark:[background-color:#5eead4]',
    solidHover: 'hover:[background-color:#115e59] dark:hover:[background-color:#99f6e4]',
  },
  charcoal: {
    text: '[color:#111827]',
    border: '[border-color:#111827]',
    lightBg: '[background-color:#e5e7eb]',
    badge: '[background-color:#e5e7eb] [color:#111827]',
    dot: '[background-color:#111827]',
    ring: 'ring-gray-300',
    solid: '[background-color:#111827] dark:[background-color:#9ca3af]',
    solidHover: 'hover:[background-color:#374151] dark:hover:[background-color:#d1d5db]',
  },
  sky: {
    text: '[color:#0369a1]',
    border: '[border-color:#0ea5e9]',
    lightBg: '[background-color:#e0f2fe]',
    badge: '[background-color:#e0f2fe] [color:#0369a1]',
    dot: '[background-color:#0ea5e9]',
    ring: 'ring-[#bae6fd]',
    solid: '[background-color:#0ea5e9] dark:[background-color:#38bdf8]',
    solidHover: 'hover:[background-color:#0284c7] dark:hover:[background-color:#7dd3fc]',
  },
  emerald: {
    text: '[color:#047857]',
    border: '[border-color:#10b981]',
    lightBg: '[background-color:#d1fae5]',
    badge: '[background-color:#d1fae5] [color:#047857]',
    dot: '[background-color:#10b981]',
    ring: 'ring-[#a7f3d0]',
    solid: '[background-color:#10b981] dark:[background-color:#34d399]',
    solidHover: 'hover:[background-color:#059669] dark:hover:[background-color:#6ee7b7]',
  },
  violet: {
    text: '[color:#6d28d9]',
    border: '[border-color:#8b5cf6]',
    lightBg: '[background-color:#ede9fe]',
    badge: '[background-color:#ede9fe] [color:#6d28d9]',
    dot: '[background-color:#8b5cf6]',
    ring: 'ring-[#ddd6fe]',
    solid: '[background-color:#8b5cf6] dark:[background-color:#a78bfa]',
    solidHover: 'hover:[background-color:#7c3aed] dark:hover:[background-color:#c4b5fd]',
  },
  fuchsia: {
    text: '[color:#a21caf]',
    border: '[border-color:#d946ef]',
    lightBg: '[background-color:#fae8ff]',
    badge: '[background-color:#fae8ff] [color:#a21caf]',
    dot: '[background-color:#d946ef]',
    ring: 'ring-[#f5d0fe]',
    solid: '[background-color:#d946ef] dark:[background-color:#e879f9]',
    solidHover: 'hover:[background-color:#c026d3] dark:hover:[background-color:#f0abfc]',
  },
  amber: {
    text: '[color:#92400e]',
    border: '[border-color:#f59e0b]',
    lightBg: '[background-color:#fef3c7]',
    badge: '[background-color:#fef3c7] [color:#92400e]',
    dot: '[background-color:#f59e0b]',
    ring: 'ring-[#fde68a]',
    solid: '[background-color:#f59e0b] dark:[background-color:#fbbf24]',
    solidHover: 'hover:[background-color:#d97706] dark:hover:[background-color:#fcd34d]',
  },
  slate: {
    text: '[color:#334155]',
    border: '[border-color:#475569]',
    lightBg: '[background-color:#f1f5f9]',
    badge: '[background-color:#f1f5f9] [color:#334155]',
    dot: '[background-color:#475569]',
    ring: 'ring-[#cbd5e1]',
    solid: '[background-color:#475569] dark:[background-color:#94a3b8]',
    solidHover: 'hover:[background-color:#334155] dark:hover:[background-color:#cbd5e1]',
  },
  zinc: {
    text: '[color:#3f3f46]',
    border: '[border-color:#52525b]',
    lightBg: '[background-color:#f4f4f5]',
    badge: '[background-color:#f4f4f5] [color:#3f3f46]',
    dot: '[background-color:#52525b]',
    ring: 'ring-[#d4d4d8]',
    solid: '[background-color:#52525b] dark:[background-color:#a1a1aa]',
    solidHover: 'hover:[background-color:#3f3f46] dark:hover:[background-color:#d4d4d8]',
  },
  stone: {
    text: '[color:#44403c]',
    border: '[border-color:#57534e]',
    lightBg: '[background-color:#f5f5f4]',
    badge: '[background-color:#f5f5f4] [color:#44403c]',
    dot: '[background-color:#57534e]',
    ring: 'ring-[#d6d3d1]',
    solid: '[background-color:#57534e] dark:[background-color:#a8a29e]',
    solidHover: 'hover:[background-color:#44403c] dark:hover:[background-color:#d6d3d1]',
  },
  magenta: {
    text: '[color:#a21caf]',
    border: '[border-color:#c026d3]',
    lightBg: '[background-color:#fae8ff]',
    badge: '[background-color:#fae8ff] [color:#a21caf]',
    dot: '[background-color:#c026d3]',
    ring: 'ring-[#f0abfc]',
    solid: '[background-color:#c026d3] dark:[background-color:#e879f9]',
    solidHover: 'hover:[background-color:#a21caf] dark:hover:[background-color:#f0abfc]',
  },
  lavender: {
    text: '[color:#6d28d9]',
    border: '[border-color:#7c3aed]',
    lightBg: '[background-color:#ede9fe]',
    badge: '[background-color:#ede9fe] [color:#6d28d9]',
    dot: '[background-color:#7c3aed]',
    ring: 'ring-[#c4b5fd]',
    solid: '[background-color:#7c3aed] dark:[background-color:#a78bfa]',
    solidHover: 'hover:[background-color:#6d28d9] dark:hover:[background-color:#c4b5fd]',
  },
  plum: {
    text: '[color:#7e22ce]',
    border: '[border-color:#9333ea]',
    lightBg: '[background-color:#f3e8ff]',
    badge: '[background-color:#f3e8ff] [color:#7e22ce]',
    dot: '[background-color:#9333ea]',
    ring: 'ring-[#d8b4fe]',
    solid: '[background-color:#9333ea] dark:[background-color:#c084fc]',
    solidHover: 'hover:[background-color:#7e22ce] dark:hover:[background-color:#d8b4fe]',
  },
  coral: {
    text: '[color:#c2410c]',
    border: '[border-color:#f9735b]',
    lightBg: '[background-color:#ffedd5]',
    badge: '[background-color:#ffedd5] [color:#c2410c]',
    dot: '[background-color:#f9735b]',
    ring: 'ring-[#fed7aa]',
    solid: '[background-color:#f9735b] dark:[background-color:#fb923c]',
    solidHover: 'hover:[background-color:#ea580c] dark:hover:[background-color:#fdba74]',
  },
  salmon: {
    text: '[color:#be123c]',
    border: '[border-color:#fb7185]',
    lightBg: '[background-color:#ffe4e6]',
    badge: '[background-color:#ffe4e6] [color:#be123c]',
    dot: '[background-color:#fb7185]',
    ring: 'ring-[#fecdd3]',
    solid: '[background-color:#fb7185] dark:[background-color:#fda4af]',
    solidHover: 'hover:[background-color:#e11d48] dark:hover:[background-color:#fecdd3]',
  },
  apricot: {
    text: '[color:#b45309]',
    border: '[border-color:#fbbf24]',
    lightBg: '[background-color:#fffbeb]',
    badge: '[background-color:#fffbeb] [color:#b45309]',
    dot: '[background-color:#fbbf24]',
    ring: 'ring-[#fde68a]',
    solid: '[background-color:#fbbf24] dark:[background-color:#fcd34d]',
    solidHover: 'hover:[background-color:#f59e0b] dark:hover:[background-color:#fde68a]',
  },
  tangerine: {
    text: '[color:#c2410c]',
    border: '[border-color:#f97316]',
    lightBg: '[background-color:#ffedd5]',
    badge: '[background-color:#ffedd5] [color:#c2410c]',
    dot: '[background-color:#f97316]',
    ring: 'ring-[#fed7aa]',
    solid: '[background-color:#f97316] dark:[background-color:#fb923c]',
    solidHover: 'hover:[background-color:#ea580c] dark:hover:[background-color:#fdba74]',
  },
  bronze: {
    text: '[color:#854d0e]',
    border: '[border-color:#a16207]',
    lightBg: '[background-color:#fef3c7]',
    badge: '[background-color:#fef3c7] [color:#854d0e]',
    dot: '[background-color:#a16207]',
    ring: 'ring-[#fde68a]',
    solid: '[background-color:#a16207] dark:[background-color:#ca8a04]',
    solidHover: 'hover:[background-color:#854d0e] dark:hover:[background-color:#eab308]',
  },
  copper: {
    text: '[color:#92400e]',
    border: '[border-color:#b45309]',
    lightBg: '[background-color:#ffedd5]',
    badge: '[background-color:#ffedd5] [color:#92400e]',
    dot: '[background-color:#b45309]',
    ring: 'ring-[#fed7aa]',
    solid: '[background-color:#b45309] dark:[background-color:#f59e0b]',
    solidHover: 'hover:[background-color:#92400e] dark:hover:[background-color:#fbbf24]',
  },
  olive: {
    text: '[color:#4d7c0f]',
    border: '[border-color:#65a30d]',
    lightBg: '[background-color:#ecfccb]',
    badge: '[background-color:#ecfccb] [color:#4d7c0f]',
    dot: '[background-color:#65a30d]',
    ring: 'ring-[#d9f99d]',
    solid: '[background-color:#65a30d] dark:[background-color:#a3e635]',
    solidHover: 'hover:[background-color:#4d7c0f] dark:hover:[background-color:#bef264]',
  },
  forest: {
    text: '[color:#166534]',
    border: '[border-color:#166534]',
    lightBg: '[background-color:#dcfce7]',
    badge: '[background-color:#dcfce7] [color:#166534]',
    dot: '[background-color:#166534]',
    ring: 'ring-[#bbf7d0]',
    solid: '[background-color:#166534] dark:[background-color:#4ade80]',
    solidHover: 'hover:[background-color:#14532d] dark:hover:[background-color:#86efac]',
  },
  seafoam: {
    text: '[color:#0f766e]',
    border: '[border-color:#14b8a6]',
    lightBg: '[background-color:#ccfbf1]',
    badge: '[background-color:#ccfbf1] [color:#0f766e]',
    dot: '[background-color:#14b8a6]',
    ring: 'ring-[#99f6e4]',
    solid: '[background-color:#14b8a6] dark:[background-color:#5eead4]',
    solidHover: 'hover:[background-color:#0f766e] dark:hover:[background-color:#99f6e4]',
  },
  aqua: {
    text: '[color:#0e7490]',
    border: '[border-color:#06b6d4]',
    lightBg: '[background-color:#cffafe]',
    badge: '[background-color:#cffafe] [color:#0e7490]',
    dot: '[background-color:#06b6d4]',
    ring: 'ring-[#a5f3fc]',
    solid: '[background-color:#06b6d4] dark:[background-color:#22d3ee]',
    solidHover: 'hover:[background-color:#0891b2] dark:hover:[background-color:#67e8f9]',
  },
  turquoise: {
    text: '[color:#0f766e]',
    border: '[border-color:#2dd4bf]',
    lightBg: '[background-color:#ccfbf1]',
    badge: '[background-color:#ccfbf1] [color:#0f766e]',
    dot: '[background-color:#2dd4bf]',
    ring: 'ring-[#99f6e4]',
    solid: '[background-color:#2dd4bf] dark:[background-color:#5eead4]',
    solidHover: 'hover:[background-color:#0d9488] dark:hover:[background-color:#99f6e4]',
  },
  steel: {
    text: '[color:#475569]',
    border: '[border-color:#64748b]',
    lightBg: '[background-color:#f1f5f9]',
    badge: '[background-color:#f1f5f9] [color:#475569]',
    dot: '[background-color:#64748b]',
    ring: 'ring-[#cbd5e1]',
    solid: '[background-color:#64748b] dark:[background-color:#94a3b8]',
    solidHover: 'hover:[background-color:#475569] dark:hover:[background-color:#cbd5e1]',
  },
  denim: {
    text: '[color:#1d4ed8]',
    border: '[border-color:#2563eb]',
    lightBg: '[background-color:#dbeafe]',
    badge: '[background-color:#dbeafe] [color:#1d4ed8]',
    dot: '[background-color:#2563eb]',
    ring: 'ring-[#bfdbfe]',
    solid: '[background-color:#2563eb] dark:[background-color:#60a5fa]',
    solidHover: 'hover:[background-color:#1d4ed8] dark:hover:[background-color:#93c5fd]',
  },
  royal: {
    text: '[color:#4338ca]',
    border: '[border-color:#4f46e5]',
    lightBg: '[background-color:#e0e7ff]',
    badge: '[background-color:#e0e7ff] [color:#4338ca]',
    dot: '[background-color:#4f46e5]',
    ring: 'ring-[#c7d2fe]',
    solid: '[background-color:#4f46e5] dark:[background-color:#818cf8]',
    solidHover: 'hover:[background-color:#4338ca] dark:hover:[background-color:#a5b4fc]',
  },
  sapphire: {
    text: '[color:#1e40af]',
    border: '[border-color:#1d4ed8]',
    lightBg: '[background-color:#dbeafe]',
    badge: '[background-color:#dbeafe] [color:#1e40af]',
    dot: '[background-color:#1d4ed8]',
    ring: 'ring-[#bfdbfe]',
    solid: '[background-color:#1d4ed8] dark:[background-color:#60a5fa]',
    solidHover: 'hover:[background-color:#1e40af] dark:hover:[background-color:#93c5fd]',
  },
  periwinkle: {
    text: '[color:#4f46e5]',
    border: '[border-color:#6366f1]',
    lightBg: '[background-color:#e0e7ff]',
    badge: '[background-color:#e0e7ff] [color:#4f46e5]',
    dot: '[background-color:#6366f1]',
    ring: 'ring-[#c7d2fe]',
    solid: '[background-color:#6366f1] dark:[background-color:#818cf8]',
    solidHover: 'hover:[background-color:#4f46e5] dark:hover:[background-color:#a5b4fc]',
  },
  orchid: {
    text: '[color:#9333ea]',
    border: '[border-color:#c084fc]',
    lightBg: '[background-color:#f3e8ff]',
    badge: '[background-color:#f3e8ff] [color:#9333ea]',
    dot: '[background-color:#c084fc]',
    ring: 'ring-[#e9d5ff]',
    solid: '[background-color:#c084fc] dark:[background-color:#d8b4fe]',
    solidHover: 'hover:[background-color:#a855f7] dark:hover:[background-color:#e9d5ff]',
  },
  raspberry: {
    text: '[color:#9f1239]',
    border: '[border-color:#be123c]',
    lightBg: '[background-color:#ffe4e6]',
    badge: '[background-color:#ffe4e6] [color:#9f1239]',
    dot: '[background-color:#be123c]',
    ring: 'ring-[#fecdd3]',
    solid: '[background-color:#be123c] dark:[background-color:#fb7185]',
    solidHover: 'hover:[background-color:#9f1239] dark:hover:[background-color:#fda4af]',
  },
  moss: {
    text: '[color:#365314]',
    border: '[border-color:#3f6212]',
    lightBg: '[background-color:#ecfccb]',
    badge: '[background-color:#ecfccb] [color:#365314]',
    dot: '[background-color:#3f6212]',
    ring: 'ring-[#d9f99d]',
    solid: '[background-color:#3f6212] dark:[background-color:#84cc16]',
    solidHover: 'hover:[background-color:#365314] dark:hover:[background-color:#a3e635]',
  },
};

export type ColorKey = keyof typeof colorClasses;
export type ColorType = keyof typeof colorClasses.blue;

export const getColorClass = (color: string | undefined | null, type: ColorType): string => {
  if (!color) return colorClasses.blue[type];
  const colorKey = color as ColorKey;
  return colorClasses[colorKey]?.[type] || colorClasses.blue[type];
};

export const getItemStyleClasses = (color: string | undefined | null): string => {
  const safeColor = color || 'blue';
  return `${getColorClass(safeColor, 'solid')} text-white dark:text-black ${getColorClass(safeColor, 'solidHover')} shadow-sm`;
};

export const getItemBgClass = (color: string | undefined | null): string => {
  return getColorClass(color, 'lightBg');
};

export const getBadgeClass = (color: string | undefined | null): string => {
  return getColorClass(color, 'badge');
};

export const getDotClass = (color: string | undefined | null): string => {
  return getColorClass(color, 'dot');
};

export const getSolidClass = (color: string | undefined | null): string => {
  return getColorClass(color, 'solid');
};
